### ISSUE TITLE
IndexError with reddit crypto scrape

### ISSUE THREAD

**Issue by ElegantEgotist** [spartan737/Stocksera#13]
When trying to scrape crypto:
> Traceback (most recent call last):
  File "tasks_to_run.py", line 83, in <module>
    scrape_reddit_crypto.main()
  File "/home/testadmin/Stocksera/scheduled_tasks/reddit/get_reddit_trending_crypto.py", line 317, in main
    
This line from get_reddit_trending_crypto.py gives an index error:
>db.execute("SELECT * FROM cryptocurrency WHERE date_updated LIKE '%{}%'".format(dates[-1][0].split()[0], ))
IndexError: list index out of range

**Comment by CodeInFilth** [comment]
> When trying to scrape crypto:
> 
> > Traceback (most recent call last):
> > File "tasks_to_run.py", line 83, in 
> > scrape_reddit_crypto.main()
> > File "/home/testadmin/Stocksera/scheduled_tasks/reddit/get_reddit_trending_crypto.py", line 317, in main
> 
> This line from get_reddit_trending_crypto.py gives an index error:
> 
> > db.execute("SELECT * FROM cryptocurrency WHERE date_updated LIKE '%{}%'".format(dates[-1][0].split()[0], ))
> > IndexError: list index out of range

Check you database files, index out of range means the varible its trying to grab is non existant. Use the google drive database he supplied in Scheduled_Tasks and  then run the procceses. Make sure you update all the settings needed and run collectscript

**Comment by spartan737** [comment]
I have fixed the bug. Replace it with:


    if dates:
        last_date = dates[-1][0].split()[0]
    else:
        last_date = ""
    db.execute("SELECT * FROM cryptocurrency WHERE date_updated LIKE '%{}%'".format(last_date, ))

**Comment by ElegantEgotist** [comment]
The fix worked. Also I didn't notice @spartan737 had updated the sample drive database since I hadn't checked it in a while. I tried with those as well and it works great. Thank you both, closing this now.
