### ISSUE TITLE
Reverse Repo broken or Site maintance?

### ISSUE THREAD

**Issue by CodeInFilth** [spartan737/Stocksera#14]
Ran the script and it failed which was intresting to me so I dug around the console and went to the supposed excel file link to get this.

```
https://websvcgatewayx2.frbny.org/autorates_tomo_external/services/v1_0/tomo/retrieveHistoricalExcel?f=01022014&t=09172021&ctt=true&&cta=true&ctm=true
```

<img width="858" alt="Screen Shot 2021-09-17 at 8 19 00 PM" src="https://user-images.githubusercontent.com/83859821/133870805-59827953-9c4c-462e-a5a8-1add56974c66.png">

**Comment by spartan737** [comment]
There's nothing wrong with the code. It seems like the web is undergoing maintenance. Please try this script again in a few days time.

**Comment by CodeInFilth** [comment]
> There's nothing wrong with the code. It seems like the web is undergoing maintenance. Please try this script again in a few days time.  

Awesome. Well I will be reviewing this code and adding in some new features I want for my DD.

Your the best at replies so far with the issues I have opened.
