### ISSUE TITLE
Hedge Funds CSVs? and Get Earnings, FTD failures

### ISSUE THREAD

**Issue by CodeInFilth** [spartan737/Stocksera#15]
Hedge Fund Holding:

I have noticed you removed your "hedge_funds_holdings" folders and also removed the code to view the files in the ViewStocks/views.py . Should i consider making my own script to update and read these or did you have a new implemented version of hedge fund holdings?

Earnings:

I have dug through the code and found these last two errors I am encountering. I could change the scripts enough to fix but don't see destroying your code as that as a smart decision just yet haha. 

```
Traceback (most recent call last):
  File "_daily_altr_tasks_to_run.py", line 121, in <module>
    get_earnings_calendar.insert_earnings_into_db(get_earnings_calendar.get_earnings(7, forward=True))
  File "/root/_production_website/Stocksera/scheduled_tasks/get_earnings_calendar.py", line 70, in get_earnings
    name = tds[1].text
IndexError: list index out of range
root@auroratrades:~/_production_website
```

I have been running into this error with the helper line changes or without it.

FTD:

This is the only error left I am reporting

```
Version 7.2.0 of praw is outdated. Version 7.4.0 was released Friday July 30, 2021.
Successfully created/updated database
Processing:  top_ftd.csv
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CUSIP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_daily_altr_tasks_to_run.py", line 129, in <module>
    get_failure_to_deliver.combine_df(folder_path=FOLDER_PATH)
  File "/root/_production_website/Stocksera/scheduled_tasks/get_failure_to_deliver.py", line 31, in combine_df
    del df["CUSIP"]
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py", line 3965, in __delitem__
    loc = self.axes[-1].get_loc(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'CUSIP'
```

**Comment by spartan737** [comment]
1. I have removed hedge funds holding section due to the lack of accessible data that I wanted.
2. The FTD script is now able to mass download from SEC website (you do not have to manually download them now).

Please try them and tell me how it goes!

**Comment by CodeInFilth** [comment]
> 1. I have removed hedge funds holding section due to the lack of accessible data that I wanted.
> 2. The FTD script is now able to mass download from SEC website (you do not have to manually download them now).
> 
> Please try them and tell me how it goes!
> 
> edit: i have included a number of new features. Do read the README.md for more details :)

Yes I noticed the web scrape for the new information, I actually implemented a version of that for an addon I made for this a couple commits ago and need to remake it for unusalwhales, whalewisdom, blackbox[as I have a paid account I can program a script to login and scrape] and flowalgo. ( I am planning on dropping them and looking at your new process as I want my plugins to be as consisten as possible. 

I always do my best to read all documentation on updates of anything and some of the tools your building I am extremely interested in, maybe I should re read them slower because a few changes happened I did not see notes of some changes I ran into issues with during an update from older files. I only see notes on these in the commit amend text.

Also very curious about your new custom_extensions folder and how to utilize this best? I am making my own plugins for my local changes but would defiantly make updating or staying organized enough for a `~ ➜ git pull` request later for updating on a proper `~ ➜ git stash`

Let me know if you ever need feedback or testing, you dont need help programing clearly haha.

**Comment by spartan737** [comment]
The custom_extensions folder (custom_words.py) supplements the NLTK library, as it is unable to get the sentiment of stock terms. For e.g., bear in stocks is negative, but using the original NLTK library, its sentiment will be neutral. stopwords.py is also used when getting popular tickers on Reddit, as there are some terms that I want to exclude, for example: Ape, Moon, Yolo, Fomo, which are obviously not stock tickers.
