### ISSUE TITLE
Options are working occasionally...

### ISSUE THREAD

**Issue by CodeInFilth** [spartan737/Stocksera#17]
I have been trying to debug this one myself but im lost now I think it has to do with cache but not sure.

Apple's Options load 10% of the time and and will never load the default date url on APPL options for whatever reason. If I select an older date its random if it is working and future dates same thing for mmost tickers.

Now I noticed there is an option to claer oold option data in the tasks to run I havnt run that yet as I am unsure of the complete reason to do so.

I also notice at the bottom of some scripts like get earnings, there is a   'delete_old_earnings("2021-10-01")', Is there an area in update ticker_info that has something similar?

I am testing on ubuntu 18.04 and will be setting up windows machine shortly.

P.S. Now I have noticed a few things in the code the one that stands out the most is within the get_financial.py more than half the document is commented out. What was the reason you left this code here? Is it for error testing or fixing like in the helpers.py?

**Comment by spartan737** [comment]
Options Data: I'm still in the midst of finding another alternative to Yahoo data, since Yahoo data is unreliable.

Retails Sales & Inflation: The website I'm scraping from recently blocked non-paying users from scraping the website. Finding alternative as well.

Earnings: It seems like your sqlite version is too old. Refer to https://stackoverflow.com/questions/54172926/unable-to-use-on-conflict. You might need to upgrade your sqlite to the latest version. FYI, I'm using python 3.7 and below is my output.

```
(venv) C:\Users\Acer\PycharmProjects\Stocksera>py scheduled_tasks/get_earnings_calendar.py
https://finance.yahoo.com/calendar/earnings?day=2021-11-04&size=100&offset=0
https://finance.yahoo.com/calendar/earnings?day=2021-11-04&size=100&offset=100
https://finance.yahoo.com/calendar/earnings?day=2021-11-04&size=100&offset=200
https://finance.yahoo.com/calendar/earnings?day=2021-11-04&size=100&offset=300
https://finance.yahoo.com/calendar/earnings?day=2021-11-04&size=100&offset=400
https://finance.yahoo.com/calendar/earnings?day=2021-11-05&size=100&offset=0
https://finance.yahoo.com/calendar/earnings?day=2021-11-05&size=100&offset=100
https://finance.yahoo.com/calendar/earnings?day=2021-11-05&size=100&offset=200
https://finance.yahoo.com/calendar/earnings?day=2021-11-05&size=100&offset=300
https://finance.yahoo.com/calendar/earnings?day=2021-11-05&size=100&offset=400
BL 2021-11-04 AMC
BLL 2021-11-04 BMO
BXRX 2021-11-04 BMO
MBIO 2021-11-04 BMO
UNRV 2021-11-04 AMC
BTCY 2021-11-04 AMC
PASG 2021-11-04 BMO
MNST 2021-11-04 AMC
PRVB 2021-11-04 BMO
VIR 2021-11-04 AMC
BLI 2021-11-04 TNS
EBS 2021-11-04 AMC
```

**Comment by CodeInFilth** [comment]
I have fixed all issues and errors with docker so I no longer can blame version control.

I do have this options error and it is not the api, I believe it has somthing to do with the caching system. Maybe I will include another API and share with you

**Comment by guanquann** [comment]
TD Ameritrade API is being used for options data now. You should have no problem getting the data now.
