### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by 3dhistory** [spartan737/Stocksera#2]
Hello,

I am getting "list index out of range" errors in reddit->trending and reddit ->WSB ETF.  The database is created and the tables seem to be there. Here is the code I ued to check the tables.

>>> import sqlite3
>>> con = sqlite3.connect('database.db')
>>> cursor = con.cursor()
>>> cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
<sqlite3.Cursor object at 0x00000248FBCF9B20>
>>> print(cursor.fetchall())

[('wallstreetbets',), ('sqlite_sequence',), ('stocks',), ('stockmarket',), ('news_sentiment',), ('reddit_etf',), ('earnings_calendar',), ('subreddit_count',), ('short_interest',), ('low_float',), ('short_volume',), ('top_DD',), ('contact',)]

What do I do wrong?

http://127.0.0.1:8000/reddit_analysis/
3.1.6
IndexError
list index out of range
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/reddit_analysis/

Django Version: 3.1.6
Python Version: 3.9.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'templatetags.filter',
 'ViewStocks']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "D:\02_Stock_Analysis\Stocksera-spartan737\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\02_Stock_Analysis\Stocksera-spartan737\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Stock_Analysis\Stocksera-spartan737\Stocksera\ViewStocks\views.py", line 555, in reddit_analysis
    date_selected = all_dates[0]

Exception Type: IndexError at /reddit_analysis/
Exception Value: list index out of range

Traceback (most recent call last):
  File "D:\02_Stock_Analysis\Stocksera-spartan737\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\02_Stock_Analysis\Stocksera-spartan737\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\02_Stock_Analysis\Stocksera-spartan737\Stocksera\ViewStocks\views.py", line 597, in reddit_etf
    unrealized_PnL = round(db.fetchone()[0], 2)

Exception Type: TypeError at /reddit_etf/
Exception Value: type NoneType doesn't define __round__ method

**Comment by spartan737** [comment]
Hello. Most probably you have not run the script to scrape data from Reddit. Please refer to [https://github.com/spartan737/Stocksera/tree/master/scheduled_tasks](https://github.com/spartan737/Stocksera/tree/master/scheduled_tasks) for more information. Run scheduled_tasks/main.py first (for reddit trending), followed by scheduled_tasks/buy_trending_ticker.py
