### ISSUE TITLE
No module named 'scheduled_tasks'

### ISSUE THREAD

**Issue by 3dhistory** [spartan737/Stocksera#3]
Something is still a miss. Where does 'scheduled_tasks' come from? I see you import it everywere but ... 

Traceback (most recent call last):
  File "D:\02_Stock_Analysis\Stocksera-spartan737\Stocksera\scheduled_tasks\main.py", line 2, in <module>
    import scheduled_tasks.get_reddit_trending_stocks.scrape_reddit as scrape_reddit
ModuleNotFoundError: No module named 'scheduled_tasks'

**Comment by spartan737** [comment]
Scheduled_tasks is a folder name found in the main directory

**Comment by spartan737** [comment]
Hi. I have rewrote the pipeline of the entire scheduled_tasks section. You only need to edit tasks_to_run.py in the main parent directory directly. I have also removed the section for due diligence, as I have decided to focus on other sections of the application first. Please clone the latest version of the repo
