### ISSUE TITLE
PYTHONPATH needed for setup with venv when running scheduled_tasks

### ISSUE THREAD

**Issue by CodeInFilth** [spartan737/Stocksera#4]
Hi love your script, as I am attempting to get it fully functionally I cannot get any of the schedulded tasks to work. I am a PHP developer exploring new ways to create a stable webapp and am stuck running your venv scripts. Is there a missing peice in the readme?

I am receiving an error similar to
```
  File "main.py", line 2, in <module>
    import scheduled_tasks.get_reddit_trending_stocks.scrape_reddit as scrape_reddit
ModuleNotFoundError: No module named 'scheduled_tasks'
```

on every file under that directory, after some research i noticed a link to the venv and packages was needed, can you help solve this issue?

Otherwise I will probably use some of your source to make a full node or PHP port.

PS Excuse my poor syntax and understanding of python in this environment as I am speaking candidly about what I see in the errors.

Thanks,
Filth

**Comment by spartan737** [comment]
Hello, thank you for your notice. I just realised that if I run my script in terminal, it will show the error you raised. However, if I run it directly (clicking on the run button in Pycharm), it works perfectly fine. Thats right, a link to the venv and packages was needed but I'm still trying to figure it out. I will probably update you again a few days later since I'm pretty busy recently. Do let me know if you find a solution!

**Comment by CodeInFilth** [comment]
thanks! yes, also might want to adjust the Ubuntu install instructions

firstly I needed extensive CPU to install grpico a warning to close any unessicary processes would be smart... could have been an error but my CPU was maxing out on my server 4.8ghz through Hostinger. 

Pandas also I had to install manuallly the support version linked to apt index seemed to be max of 1.1.5. I had to uninstall manually, reinstall through the github shell and then reinstall the requirements, to fix the links.

If you need me to DM you further I can help.

**Comment by CodeInFilth** [comment]
The default django user and password would be preferable also.

**Comment by spartan737** [comment]
Hi. I have rewrote the pipeline of the entire scheduled_tasks section. You only need to edit tasks_to_run.py in the main parent directory directly. I have also removed the section for due diligence, as I have decided to focus on other sections of the application first. Please clone the latest version of the repo

**Comment by spartan737** [comment]
Please like Stocksera if you enjoy the application 🤩
